""" 
This file contains low level utility methods for operating with Rhythm Continuities 
"""
def get_rhythmic_resultant_from_generators(*generators: int, cp: int): 
    """
    This method creates arrays of '0' (rests) and '1' (beats) for multiple monomial periodicities.
    Then combines all rhythmic patterns dropping them perpendicularly
    Args:
        *generators: variable number of integer generators
        cp (int): common period
    Returns:
        array: rhythmic resultant of all periodicities
    """
    arrays = [generate_rhythm_str(gen, cp) for gen in generators]
    # Pass arrays as separate arguments using *
    return merge_rhythmical_continuities(*arrays)

def merge_rhythmical_continuities(*continuities: list):
    """
    Given 'n' rhythm continuities as lists of '0' and '1', returns a list
    that represents the superimposition of said continuities
    
    Example:
        >>> merge_rhythmical_continuities([1, 0, 0], [0, 1, 0], [1, 0, 0])
        [1, 1, 0]
    """
    return [1 if any(x == 1 for x in values) else 0 
            for values in zip(*continuities)]

def generate_rhythm_str(gen: int, cp: int):
    """
    Returns a rhythm list where '1' marks periodic attacks every 'gen' steps.

    Args:
        gen (int): The generator step (periodicity).
        cp (int): The common product or total length of the sequence.

    Returns:
        list: A list of integers (0 or 1) representing the rhythm pattern.

    Example:
        >>> generate_rhythm_str(2, 6)
        [1, 0, 1, 0, 1, 0]
    """
    return [int(i % gen == 0) for i in range(cp)]

    
def split_in_measures(cont: list, measure_length: int):
    """
    This method splits the given sequence of '0' and '1' into sub-arrays (eq. to bars), 
    each bar being equal to measure_length
    Args:
        cont (list of list of int): the given rhythmic continuity
        measure_length (int): number of beats per bar
    Returns:
        cont: original continuity now divided in sub-arrays (bars)
    """
    return [cont[i:i + measure_length] for i in range(0, len(cont), measure_length)]

def replace_rests(sequence: list):
    """
    This method adds consecutive rests (0s) to the previous beat value,
    creating a rhythmic continuity where rests extend the previous note duration.
    Example:
        Input:  [1,0,0,1,0,0,1]
        Output: [3,3,1]
    Args:
        sequence (list): a list of 0s and 1s representing beats and rests
    Returns:
        list: sequence where rests are added to previous beat duration
    """
    result = []
    i = 0
    while i < len(sequence):
        if sequence[i] == 1:
            count = 1
            # Count consecutive zeros after this beat
            while i + count < len(sequence) and sequence[i + count] == 0:
                count += 1
            result.append(count)
            i += count
        else:
            i += 1  # Skip initial rests
    
    return result

def generate_fractioning_from_min_gen(a: int, b: int, indexes: list):
    """
    Generates multiple rhythm patterns based on a minimal generator and aligns them at given indexes.

    Each rhythm pattern is created by repeating a binary sequence generated by `generate_rhythm_str(b, a * b)`,
    and is inserted at the specified index in a zero-filled array of length `a * a`.

    If a generated group exceeds the allowed length (`a * a`), it is skipped.

    Args:
        a (int): The base number used to define the total output length (`a * a`) and rhythm length (`a * b`).
        b (int): The minimal generator that defines rhythmic periodicity.
        indexes (list): A list of starting indexes for each rhythm pattern.

    Returns:
        list: A list of lists, each containing a rhythm pattern (as 0s and 1s) of length `a * a`.

    Example:
        >>> generate_fractioning_from_min_gen(3, 2, [0, 3, 6])
        [
            [1, 0, 1, 0, 1, 0, 0, 0, 0],
            [0, 0, 0, 1, 0, 1, 0, 1, 0],
            [0, 0, 0, 0, 0, 0, 1, 0, 1]
        ]
    """
    arr = []
    max_len = a * a
    rhythm_len = a * b

    for index in indexes:
        group = [0] * index if index != 0 else []
        group[index:index] = generate_rhythm_str(b, rhythm_len)
        
        if len(group) > max_len: break

        group += [0] * (max_len - len(group))  #adds '0' until end of sequence if needed
        arr.append(group)

    return arr